Check point
DiyorMarket/CheckDrive.Web pull request #246
Opened 2024-12-11 14:34 UTC by aXayitov

![Снимок экрана 2024-12-11 193056](https://github.com/user-attachments/assets/bde782e6-32b8-41e2-98fc-1958a4b81ed9)
CheckPoint

![image](https://github.com/user-attachments/assets/fc87f94f-afe7-4deb-a264-f8dbdb7cb9ed)
CheckPoint table in Dashboard. There is a problem, the problem is i couldn't made the table bigger.

2024-12-11 17:42 UTC, Boburm1rzo requested changes

2024-12-11 17:42 UTC, Boburm1rzo commented on CheckDrive.Web/CheckDrive.Web/Views/Dashboard/Index.cshtml
> +                          dataSource="@ViewBag.CheckPoint" gridLines="None">
There is more space left on the left side of the checkpoint grid, is it possible to reduce this space?

2024-12-11 17:42 UTC, Boburm1rzo commented on CheckDrive.Web/CheckDrive.Web/Views/Dashboard/Index.cshtml
>                  <ejs-grid id="resent-debts" allowPaging="true"
Since there are no debts in the current situation, the id should also be changed from resent-debts to resent-checkpoints

2024-12-18 16:36 UTC, Mirazyzz commented
@aXayitov please fix merge conflicts.

2024-12-23 12:08 UTC, Boburm1rzo approved these changes

2024-12-23 15:51 UTC, Mirazyzz approved these changes
can be merged

2024-12-23 15:51 UTC, merged